name: Deploy on PR comment

on:
  issue_comment:

jobs:
  runs-on: ubuntu-latest
  if: ${{ github.event.issue.pull_request && github.event.comment.body == '/deploy' }}
  steps:
    - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.issue.pull_request.head.sha }}
    - name: React to comment
      uses: actions/github-script@v4
        with:
          script: |
            const {owner, repo} = context.issue
            github.reactions.createForIssueComment({
              owner,
              repo,
              comment_id: context.payload.comment.id,
              content: "rocket",
            });
    - name: Run dummy deployment
      run: cat README.md
