name: First interaction

on:
  issues:
    types: [ opened ]

jobs:
  interaction:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          Thank you for posting an issue!
          
          As a reminder, have you checked the [wiki](https://github.com/jannekem/actions-playground/wiki) for common issues?
        pr-message: |
          Thank you for your first contribution to the project! I will take a look at you pull request as soon as possible. In the meantime, you should check that your PR follows the contributor guidelines. This will make it easier to review the code and get it merged faster. Thanks!
