name: PR Labeler

on: workflow_dispatch

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - uses: faiak/actions/action.yml@main
      with:
        APPCENTER_API_TOKEN: ${{ secrets.APPCENTER_ACCESS_TOKEN }}
        APPCENTER_PROJECT_NAME: ${{ secrets.APPCENTER_PROJECT_NAME_ANDROID }}
        # BRANCH: ${{ github.head_ref || github.ref_name }}
        BRANCH: releases/v0.0.3
